/* eslint-disable */
export {};

interface Fetcher {
	fetch(request: Request): Promise<Response>;
}
// Generated by Wrangler by running `wrangler types --env-file=.env.example --include-runtime=false --strict-vars=false`
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	PUBLIC_APP_URL: string;
	PORT: string;
	VITE_API_BASE: string;
	VITE_CONVEX_URL: string;
	CONVEX_URL: string;
	CONVEX_DEPLOYMENT: string;
	CONVEX_SERVICE_TOKEN: string;
	OPENROUTER_API_KEY: string;
	WISE_API_TOKEN: string;
	WISE_PROFILE_ID: string;
	WISE_ENVIRONMENT: string;
	WISE_BALANCE_IDS: string;
	REVOLUT_ENVIRONMENT: string;
	REVOLUT_REFRESH_TOKEN: string;
	REVOLUT_CLIENT_ASSERTION_JWT: string;
	SLASH_API_KEY: string;
	SLASH_LEGAL_ENTITY_ID: string;
	SLASH_BASE_URL: string;
	AMEX_TOKEN_URL: string;
	AMEX_API_BASE_URL: string;
	AMEX_CLIENT_ID: string;
	AMEX_CLIENT_SECRET: string;
	AMEX_REFRESH_TOKEN: string;
	AMEX_ACCOUNT_IDS: string;
	AMEX_ACCOUNT_PATH_TEMPLATE: string;
	AMEX_TRANSACTIONS_PATH_TEMPLATE: string;
	MERIT_API_BASE_URL: string;
	MERIT_GET_INVOICES_PATH: string;
	MERIT_CREATE_INVOICE_PATH: string;
	MERIT_DELIVER_INVOICE_PATH: string;
	MERIT_API_ID: string;
	MERIT_API_KEY: string;
	MERIT_WRITES_ENABLED: string;
	MERIT_DEFAULT_ITEM_CODE: string;
	MERIT_DEFAULT_COUNTRY_CODE: string;
	REVENUE_TIMEZONE: string;
	KISSTERRA_TUNE_NETWORK_ID: string;
	KISSTERRA_TUNE_API_KEY: string;
	KISSTERRA_TUNE_API_BASE_URL: string;
	COINBASE_EXCHANGE_RATES_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_APP_URL" | "PORT" | "VITE_API_BASE" | "VITE_CONVEX_URL" | "CONVEX_URL" | "CONVEX_DEPLOYMENT" | "CONVEX_SERVICE_TOKEN" | "OPENROUTER_API_KEY" | "WISE_API_TOKEN" | "WISE_PROFILE_ID" | "WISE_ENVIRONMENT" | "WISE_BALANCE_IDS" | "REVOLUT_ENVIRONMENT" | "REVOLUT_REFRESH_TOKEN" | "REVOLUT_CLIENT_ASSERTION_JWT" | "SLASH_API_KEY" | "SLASH_LEGAL_ENTITY_ID" | "SLASH_BASE_URL" | "AMEX_TOKEN_URL" | "AMEX_API_BASE_URL" | "AMEX_CLIENT_ID" | "AMEX_CLIENT_SECRET" | "AMEX_REFRESH_TOKEN" | "AMEX_ACCOUNT_IDS" | "AMEX_ACCOUNT_PATH_TEMPLATE" | "AMEX_TRANSACTIONS_PATH_TEMPLATE" | "MERIT_API_BASE_URL" | "MERIT_GET_INVOICES_PATH" | "MERIT_CREATE_INVOICE_PATH" | "MERIT_DELIVER_INVOICE_PATH" | "MERIT_API_ID" | "MERIT_API_KEY" | "MERIT_WRITES_ENABLED" | "MERIT_DEFAULT_ITEM_CODE" | "MERIT_DEFAULT_COUNTRY_CODE" | "REVENUE_TIMEZONE" | "KISSTERRA_TUNE_NETWORK_ID" | "KISSTERRA_TUNE_API_KEY" | "KISSTERRA_TUNE_API_BASE_URL" | "COINBASE_EXCHANGE_RATES_URL">> {}
}

export type WorkerEnv = Env;
export interface WorkerScheduledController {
	readonly scheduledTime: number;
	readonly cron: string;
	noRetry(): void;
}
export interface WorkerExecutionContext {
	waitUntil(promise: Promise<unknown>): void;
}
export interface WorkerExportedHandler {
	fetch(request: Request, env: Env, ctx: WorkerExecutionContext): Response | Promise<Response>;
	scheduled?(controller: WorkerScheduledController, env: Env, ctx: WorkerExecutionContext): void | Promise<void>;
}
