export const transactionCategoryOptions = [
  "Revenue",
  "Refunds and chargebacks",
  "Capital movement",
  "Ad account funding",
  "Ad spend",
  "Software subscription",
  "Cloud and hosting",
  "Food and meals",
  "Travel",
  "Salary and payroll",
  "Contractors and freelancers",
  "Taxes and government",
  "Office and rent",
  "Payment processing",
  "Bank fees",
  "Legal and accounting",
  "Recruiting",
  "Education and training",
  "Marketing tools",
  "Telecom and internet",
  "Equipment",
  "Insurance",
  "Utilities",
  "Security and compliance",
  "Shipping and postage",
  "Internal transfer",
  "Uncategorized"
] as const;
